name: Build OpenWrt for Phicomm N1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Clone OpenWrt source
        run: git clone --depth=1 https://github.com/openwrt/openwrt.git

      - name: Copy feeds.conf.default
        run: cp ./feeds.conf.default ./openwrt/feeds.conf.default

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libncurses5-dev zlib1g-dev gawk git gettext libssl-dev \
            xsltproc libxml-parser-perl unzip file wget python3 python3-netifaces

      - name: Update and install feeds
        working-directory: openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy defconfig
        run: cp ../configs/n1_defconfig .config
        working-directory: openwrt

      - name: Prepare config
        working-directory: openwrt
        run: yes "" | make defconfig

      - name: Build firmware
        working-directory: openwrt
        run: make -j$(nproc)

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: openwrt/bin/targets/**/*
